create table if not exists users
(id bigint generated by default as identity,
 email varchar(255) not null,
 password varchar(500) not null,
 role varchar(255),
 address text,
 panNumber text,
 adhaarCard text,
 phoneNumber text,
 primary key (id))
