create table questions
(id bigint generated by default as identity,
 questionContent varchar(500) not null,
 option1 varchar(500) not null,
 option2 varchar(500) not null,
 option3 varchar(500) not null,
 option4 varchar(500) not null,
 answer varchar(500) not null,
 primary key (id))